# .github/workflows/chromatic.yml

name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # 👇 Chromatic projectToken, referring to the secret we will set up
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
